### ISSUE TITLE
Own Adapters not used

### ISSUE THREAD

**Issue by pahlgrimm** [gzoller/ScalaJack#141]
Hi, I wrote my own BasicTypeAdapter for LocaDateTime and use it by calling ScalaJack().withAdapters(LocalDateTimeAdapter).read[B](var), but ScalaJack always uses its own LocalDateTimeTypeAdapter.

Am I missing something?

**Comment by gzoller** [comment]
Don't extend BasicTypeAdapter.  Extend SimpleTypeAdapter and it should work fine.  There's a subtle but crucial difference between the two.  The Simple variant is going to be the right choice for 99% of the people 99% of the time.

**Comment by gzoller** [comment]
I'm closing this but please do re-open it (and include code samples) if the above advice didn't work.  Hope you're enjoying ScalaJack!
