### ISSUE TITLE
Large Documents and Enum Ordinals

### ISSUE THREAD

**Issue by jayv** [gzoller/ScalaJack#144]
Couldn't parse a 6MB JSON Doc and couldn't map Enums to their Ordinal.
See https://github.com/gzoller/ScalaJack/pull/143

**Comment by jayv** [comment]
Any ideas or suggestions? @gzoller

**Comment by gzoller** [comment]
Out for a bit.   Can you share more info about this data set.  Is this one, massive 6MB single record, or 6MB of a list of smaller records?  What kind of error are you seeing?  (sorry, I have to ask...) Are you 100% sure there is not malformed/nonstandard JSON in the document?   6MB is pretty big, so this may not work, but if possible you can cut/paste into here and see if it complains: http://www.jsoneditoronline.org/  

I'll have a look at the Ordinal, including your PR.

**Comment by jayv** [comment]
Yes it's a huge 6MB doc in mongo, it's valid (one of the nested properties
is a list of 6000 subdocuments and that's where I think it went out of
bounds at 1024 mark). It parses fine in my SJ fork once I made those
changes to increase buffer sizes. While unusual, I think Mongo allows 16MB
 now so maybe those params can be configurable as its obviously a memory
hog and shouldnt be the default.

I'll see if I can fabricate a testcase today

**Comment by gzoller** [comment]
Looking at your pull request now.  You've bumped the CSV & Mongo token pool way up.  In current release, JSON should auto-scale.  Are your problems around a Mongo or CSV large file?  I should probably go back and reverse-engineer what we did for JSON into the other two, so they can auto-scale too.

**Comment by jayv** [comment]
I went in quick and dirty to get past the crash, so I may have bumped a
value that wasn't needed. In my case it's a huge Mongo document, no CSV.


- Jo Voordeckers

**Comment by gzoller** [comment]
Ok, no worries.  I took a bit from your PR but implemented the auto-grow from JSON into CSV and Mongo.  I *think* it should work.  It's all sitting in a branch feature/enumord.  Check it out and let me know if this works.  If so I'll push that content out in a release.

**Comment by jayv** [comment]
It works fine, thx for the quick fix! Any timeline for the release?

- Jo Voordeckers

**Comment by gzoller** [comment]
Soon, I hope.  I want to support 2.12 so I need to figure out how to do cross build and publish for 2 packages in sbt.

**Comment by gzoller** [comment]
5.0.4 is out.  I'm closing this.  Let me know if it didn't work in the final release.  All the functional changes should work.  Sadly I'm having issues with 2.12 support, so that's not quite there.  Soon.
