### ISSUE TITLE
Q: Is it possible to map field names

### ISSUE THREAD

**Issue by jayv** [gzoller/ScalaJack#150]
I sometime have to deal with JSON or Mongo documents with underscores in field names that I want mapped to camelCased fields in Scala or name them something completely different. It's not clear to me from the samples and docs if there is an easy way to map field names like in Jackson with the @JsonProperty and @JsonIgnore annotations on properties in a class definition?

**Comment by gzoller** [comment]
Great question.  No, sadly.   We looked at having this feature, and we had a really good reason for not doing this now--I just forgot what it was.  So for now you could either suffer the underscores or have an interim class you map into your final one.  This may be something we re-consider in the future.  I can certainly see the utility, especially when reading 3rd party JSON you don't own.

As far as ignoring fields, that's easy!  Just ignore them.  ScalaJack doesn't care about "extra" fields in the JSON, so if you have some big record but only care about 3 fields, just make a Scala class having those 3 fields.  The rest will be ignored.

**Comment by gzoller** [comment]
Hang on...  I think I've got an approach for field name mapping.  Gotta work it for case/non-case over JSON and Mongo.

Oh... I was half wrong about ignore.  ScalaJack does have an @Ignore annotation for non-case classes only (because we have to guess what fields are being serialized--no handy case class helpers).  Case classes work as mentioned above.

**Comment by gzoller** [comment]
Watch for 5.0.6 a bit later today.  I've added a @MapName annotation that allows you to map a field's name to something else, like the example you mentioned.  It works for JSON and Mongo, including fields in Mongo you identified as a key with @DBKey (and also compound keys).

**Comment by jayv** [comment]
Awesome!
