### ISSUE TITLE
ScalaJack no longer recognizes type alias for a Map

### ISSUE THREAD

**Issue by Philippus** [gzoller/ScalaJack#171]
In my code I have a type alias for a `Map[String, Any]`. If I use this type alias in a `sj.read[<type alias>]`-call I get an `Exception: co.blocke.scalajack.model.ReadUnexpectedError: [<tokenizing>]`. If I change it to `sj.read[Map[String, Any]]` it works.
Previously (before 6.0.0) I could use the type alias.

**Comment by gzoller** [comment]
Hmm, that’s a good catch.  Let me have a look...

**Comment by gzoller** [comment]
Ok, on first trial... I didn't get an exception, but it did produce erroneous results.  Here's what I tried:

```scala
  val sj = ScalaJack()
  type M = Map[String, Any]

  val m: M = Map("a" -> 2, "b" -> 1)
  val js = sj.render(m)
  println(js)
  println(sj.read[M](js))

```
This produced output:

```
{"\"a\"":2,"\"b\"":1}
Map(a -> 2, b -> 1)
```
So I don't see an exception, but I do see erroneous extra quotes rendered for the Map key strings.  I'm going to work on those.  if you have an example clip I can try that produces the exception, please post to this issue so I can hunt that one too.

**Comment by gzoller** [comment]
Think I got it.  I fixed the extra quotes problem and immediately saw the tokenizing exception.  Same problem--one on read the other on render.  That one's staged for 6.0.1 I'll post shortly after looking into the Any issue.

**Comment by Philippus** [comment]
Thanks, upgrade now went smoothly in https://github.com/Philippus/baggage-jwt/pull/13
