### ISSUE TITLE
6.2.0 no longer available

### ISSUE THREAD

**Issue by Philippus** [gzoller/ScalaJack#237]
Since the JCenter [Sunset](https://jfrog.com/blog/jcenter-sunset/), scalajack 6.2.0 is no longer available. Could you release that version to maven central?

**Comment by gzoller** [comment]
Surely--it may take a day or two.  Gotta rebuilt that version and update it (and the github workflows) to get it to publish properly on maven central like the newer versions.

**Comment by gzoller** [comment]
Hello, sorry for the delay. Getting this old/sleeping version published wasn't easy. Dealing with pgp, sonatype, etc is a headache!  I managed (I think) to get core ScalaJack 6.2.0 published to sonatype, so you should be able to see it. I wasn't able to get the mongo, dynamo, etc modules out. Not working for some reason. Hopefully you're not depending on them.

**Comment by Philippus** [comment]
Thanks!
