### ISSUE TITLE
Error message when mapping json to scala object

### ISSUE THREAD

**Issue by CharlesAHunt** [gzoller/ScalaJack#5]
This message is received when incorrectly attempting to map a json string value to a Scala Int:   

java.lang.IllegalArgumentException: Expected VALUE_STRING and saw VALUE_STRING

For example: 
    pl1$episodeNumber          : Option[Int] 
should have been
    pl1$episodeNumber          : Option[String] 
for JSON element
   "pl1$episodeNumber": "208H",

message should be:  java.lang.IllegalArgumentException: Expected VALUE_INT and saw VALUE_STRING

**Comment by gzoller** [comment]
Well... the latest version (4.4.6) is more relaxed about such things.  Unquoted primitives will be marshaled as they would be unquoted.  There have been a *lot* of good changes to ScalaJack over the last couple months, including a big one I'm just about to publish (4.5.0) to support the new async mongo drivers.  That one may be buggy on first release.

I've added support for Any-typed values, human-friendly custom type hint mapping (so 3rd party json hint of "Foo" can be mapped to "com.mycom.Foo"), support for tuples, support for default fields in case classes... and a nice pile of bug fixes.  Check it out.
