### ISSUE TITLE
can resolve version 4.7.0

### ISSUE THREAD

**Issue by emanresusername** [gzoller/ScalaJack#50]
```text
[error] (*:update) sbt.ResolveException: unresolved dependency: co.blocke#scalajack_2.11;4.7.0: not found
[error] unresolved dependency: co.blocke#scalajack_mongo_2.11;4.7.0: not found
```

**Comment by gzoller** [comment]
Hmm... What version of sbt are you using?  0.13.9 comes pre-baked to look in bintray.
I cleared my ivy caches and rebuilt a project using ScalaJack and was able to find the files:

[info] downloading https://jcenter.bintray.com/co/blocke/scalajack_2.11/4.7.0/scalajack_2.11-4.7.0.jar ...
[info] 	[SUCCESSFUL ] co.blocke#scalajack_2.11;4.7.0!scalajack_2.11.jar (3682ms)
[info] downloading https://jcenter.bintray.com/co/blocke/scalajack_mongo_2.11/4.7.0/scalajack_mongo_2.11-4.7.0.jar ...
[info] 	[SUCCESSFUL ] co.blocke#scalajack_mongo_2.11;4.7.0!scalajack_mongo_2.11.jar (3440ms)
[info] Done updating.

**Comment by gzoller** [comment]
My sbt:

	val scalajack       = "co.blocke"                         %% "scalajack"                        % "4.7.0"
	val scalajack_mongo = "co.blocke"                         %% "scalajack_mongo"                  % "4.7.0"

**Comment by emanresusername** [comment]
weird, i'm on sbt 13.11, and it works on 4.6.0, blew away my whole ivy cache . . . still no dice :(

**Comment by emanresusername** [comment]
looks like it's optional in [0.13.11](https://github.com/sbt/sbt/releases/tag/v0.13.11)
just need to add
```sbt
useJCenter := true
```

**Comment by gzoller** [comment]
That's strange they'd change that, but good to know--thanks!  I thought the whole typesafe stack was committing to bintray by default.  I guess its something people will have to know--I don't think there's anything I can add to this project that forces configuration on the consuming project.
