### ISSUE TITLE
Custom renderings for Java objects do not work with MongoFlavor()

### ISSUE THREAD

**Issue by tksmrch** [gzoller/ScalaJack#66]
Hi gzoller, 

This is such an awesome product. I really like the simple, intuitive interface and the easy integration with MongoDB. My team just started to experiment with ScalaJack in the hope that ScalaJack will greatly simplify our code related to object persistency . 

We just ran into an issue with custom renderings of Java classes using VistorContext. We are able to render a Java class with the default Jack flavor while using MongoFlavor. 

I'd highly appreciate if you could give us any thoughts around this. 

Best regards, 

Exception in thread "main" scala.MatchError: JavaType(com.instinet.gtr.exchange.ExchangeId) (of class co.blocke.scalajack.JavaType)
	at co.blocke.scalajack.mongo.MongoJackFlavor$MongoReadRenderer.co$blocke$scalajack$mongo$MongoJackFlavor$MongoReadRenderer$$_render(MongoFlavor.scala:232)
	at co.blocke.scalajack.mongo.MongoJackFlavor$MongoReadRenderer.render(MongoFlavor.scala:38)
	at co.blocke.scalajack.mongo.MongoJackFlavor$MongoReadRenderer.render(MongoFlavor.scala:33)
	at co.blocke.scalajack.ScalaJack$class.render(ScalaJack.scala:30)
	at co.blocke.scalajack.mongo.MongoFlavor$MongoScalaJack.render(MongoFlavor.scala:28)

**Comment by gzoller** [comment]
Some info will help me help you.  What version of ScalaJack are you using?  If I understand your note, you're interested in the Mongo rendering and that the JSON rendering is working OK for you, is that right?  What would really help me is if you could post a gist of a simple snip of code--your class (especially value class), how you're setting up your VisitorContext, and the ScalaJack invocation.  I'll have a look.

Glad you like ScalaJack!

**Comment by tksmrch** [comment]
Hi Greg, 

Thanks for your reply. And yes, JSON rendering is working while I want to use Mongo rendering which isn't working. Additionally, I can't convert JSON string back into a Java object using the default flavor, either. 

I'm using ScalaJack 4.8.3 with Java 8.  

I'm pasting my sample code here. Although I'm not sure if my Java class fits the definition of a "value class," it requires only one value (int) to instantiate the class. 

`
// Java value class
public class MyJavaDate
{
    private final int year;
    private final int month;
    private final int day;

    public MyJavaDate(int year, int month, int day) {
        this.year = year;
        this.month = month;
        this.day = day;
    }

    public int toYYYYMMDD() {
        return year * 10000 + month * 100 + day;
    }

    public static MyJavaDate fromYYYYMMDD(int yyyymmdd) {
        int year  = yyyymmdd / 10000;
        int month = (yyyymmdd - year * 10000) / 100;
        int day   = yyyymmdd - year * 10000 - month * 100;

        return new MyJavaDate(year, month, day);
    }
}


// Scala app
object ScalaJackCustomHandler extends App
{
  val MyJavaDateHandler = CustomReadRender(
    {
      case (j:JsonKind, yyyymmdd:Int) => MyJavaDate.fromYYYYMMDD(yyyymmdd)
    },
    {
      case (j:JsonKind, date:MyJavaDate) => date.toYYYYMMDD
    }
  )

  val HandlerMap = Map(
    "com.instinet.gtr.research.mongo.tutorial.data.MyJavaDate" ->  MyJavaDateHandler
  )

  val vc = VisitorContext().copy(customHandlers = HandlerMap)

  val date = new MyJavaDate(2016, 8, 10)

  val sjPlain  = ScalaJack()
  val sjMongo  = ScalaJack(MongoFlavor())


  //--- Serialization
  val dateJson = sjPlain.render(date, vc)
  println(dateJson)                       // => 20160810

  val dateDoc = sjMongo.render(date, vc)  // Error
  println(dateDoc)

  //--- Deserialization
  sjPlain.read[MyJavaDate](dateJson)      // Error
}
`

**Comment by gzoller** [comment]
Ok, I think I've got something for you.  You may be mixing two distinct features of ScalaJack.  The pattern for custom rendering you're using (with vc) is new, and is tailored for overriding primitives defined in ScalaJack ([these here](https://github.com/gzoller/ScalaJack/blob/master/core/src/main/scala/co.blocke.scalaJack/PrimitiveTypes.scala)).  That way you can have something like a String field for phone number and read/render it as xxx-xxx-xxxx.

What you're asking about is a value class, which is specifically a Scala (not Java) class that inherits from AnyVal.  There's a different pattern for custom rendering of these.  I've included a sample here.  See if this is kinda what you're going for.  (There are lib to manage date formatting but for simplicity I copied what you had here.)

```scala
// Your basic value class
class MyJavaDate(val yyyymmdd:Long) extends AnyVal 

// And some sample class that uses it... Just to make rendering useful.
case class Sample( name:String, sometime: MyJavaDate ) 

// Custom rendering pattern: Use a companion object to your value class
// that extends ValueClassCustom
object MyJavaDate extends ValueClassCustom {

  // Formatting helpers
  private def toYMD(yyyymmdd:Long) = {
    val year = yyyymmdd / 10000
    val month = (yyyymmdd - year * 10000) / 100
    List(year, month, yyyymmdd - year * 10000 - month * 100)
  }
  private def fromYMD( d:List[Int] ) =  d(0) * 10000 + d(1) * 100 + d(2)
    
  // Custom renderers... Note different ones for JSON and Mongo.
  // No custom stuff defined for Mongo == crash!
  def read = {
      case (j:JsonKind,js:String) => fromYMD( js.split("-").toList.map(_.toInt) )
      case (j:MongoKind,m:BsonString) => fromYMD( m.getValue.split("-").toList.map(_.toInt) )
  }
  def render = {
      case (j:JsonKind,myJavaDate:Long) => '"' + toYMD(myJavaDate).mkString("-") + '"'
      case (j:MongoKind,myJavaDate:Long) => new org.bson.BsonString(toYMD(myJavaDate).mkString("-"))
  }
}
```

Usage:

```scala
  val sample = Sample("Fred",new MyJavaDate(20160810))

  // JSON
  val sjPlain = ScalaJack()
  val js = sjPlain.render(sample)
  println( js )
  val fromJS:Sample = sjPlain.read[Sample](js)
  println(fromJS)
  println(new MyJavaDate(20160810))  // Just to show its creating the right thing
  println(fromJS.sometime.yyyymmdd)

  // MongoDB
  val sjMongo = ScalaJack(MongoFlavor())
  val m = sjMongo.render(sample)
  println( m )
  val fromMongo:Sample = sjMongo.read[Sample](m)
  println(fromMongo)
  println(fromMongo.sometime.yyyymmdd)
```

Output looks like this:

```
{"name":"Fred","sometime":"2016-8-10"}
Sample(Fred,com.cof.conversation.MyJavaDate@133a12a)
com.cof.conversation.MyJavaDate@133a12a
20160810
Document((name,BsonString{value='Fred'}), (sometime,BsonString{value='2016-8-10'}))
Sample(Fred,com.cof.conversation.MyJavaDate@133a12a)
20160810
```

You can finesse the formatting of the date output to taste, but that's the basic idea.

**## Now.... All that said...** you have an alternative if you like the new style--overriding primitives (Long in this example).  That would involve creating a type to differentiate your "special" date/long from all the other Longs out there.  It might look like this:

```scala
object Overrides {  
  type MY_DATE = Long   // Define your custom type
}
import Overrides._

// Example class to use a MY_DATE.  Note inclusion of a vanilla Long so you
// can verify that field won't get the formatting treatment.
case class Alternate(name:String, sometime:MY_DATE, num:Long)
```

And use like (with VisitorContext), not far from where you started:

```scala
  // Formatting helpers
  def toYMD(yyyymmdd:Long) = {
    val year = yyyymmdd / 10000
    val month = (yyyymmdd - year * 10000) / 100
    List(year, month, yyyymmdd - year * 10000 - month * 100)
  }
  def fromYMD( d:List[Int] ) =  d(0) * 10000 + d(1) * 100 + d(2)
  
  // Read-Render pairs
  val dateHandler = CustomReadRender(
    {
      case (j:JsonKind, js:String) => fromYMD( js.split("-").toList.map(_.toInt) )
      case (j:MongoKind,m:BsonString) => fromYMD( m.getValue.split("-").toList.map(_.toInt) )
    },
    {
      case (j:JsonKind, date:Long) =>'"' + toYMD(date).mkString("-") + '"'
      case (j:MongoKind,myJavaDate:Long) => new org.bson.BsonString(toYMD(myJavaDate).mkString("-"))
    }
  )

  // Map this to your special type defined in Overrides
  val HandlerMap = Map(
    "com.mypath.Overrides.MY_DATE" -> dateHandler
  )
  val vc = VisitorContext().copy(customHandlers = HandlerMap)

  // Now create an object
  val alt = Alternate("Mike", 20160810, 5L)

  // JSON
  val js2 = sjPlain.render(alt, vc)  // <-- Don't forget vc here!
  println( js2 )
  val fromJS2:Alternate = sjPlain.read[Alternate](js2, vc)
  println(fromJS2)

  // MONGO
  val m2 = sjMongo.render(alt, vc)
  println( m2 )
  val fromMongo2:Alternate = sjMongo.read[Alternate](m2, vc)
  println(fromMongo2)
```

This produces output:

```
{"name":"Mike","sometime":"2016-8-10","num":5}
Alternate(Mike,20160810,5)
Document((name,BsonString{value='Mike'}), (sometime,BsonInt64{value=20160810}), (num,BsonInt64{value=5}))
Alternate(Mike,20160810,5)
```

**Comment by tksmrch** [comment]
Thanks for your detailed note. Now I got a better idea about custom rendering and value class. 

What I am actually looking for is a way to serialize Java classes with ScalaJack by passing an encoder/decoder. I develop in Scala but rely heavily on my org's proprietary Java code, and so my data objects (Scala case classes) often contain Java classes as their fields. Currently I create a case class corresponding to each of such Java classes to store them in Mongo, but it would be nicer to be able to render/read the Java classes as is. 

I understand ScalaJack does not currently have this feature. But it seems like it can at least render a Java object through the VisitorContext mechanism. Is there a way to make deserialization work? Or, do you plan to support such a feature in the near term? 

Best, 
Takeshi

**Comment by gzoller** [comment]
Hmm... That might be an issue in the current version.  You could probably override some simple Java primitives, but Java collections likely wouldn't work, and Java objects absolutely wouldn't work.

Serialization isn't so hard--JSON/Mongo have pretty loose typing.  The hard part is deserialization.  The Scala object needs very (very) specific types that I just can't guess.  Your thought about accepting some kind of encoder/decoder would work but needs to be baked into the core of the parser.

I'm not sure I'd bake this into future ScalaJack versions or not--I'll have to think on that a while.  The whole point of ScalaJack is "unaided" parsing, which is what's different about parsing Java.  Those parsers need a lot of help (annotations, helper classes or something).  Adding more complex encoder/decoder logic pulls ScalaJack further from its mission and closer to products that already do a great job parsing pure Java.  Just thinking out loud--maybe I could figure out how to glom some kind of adapter to Jackson or something for Java items, for a hybrid approach: ScalaJack just hands pieces of JSON to Jackson for the Java bits?  Hmm....

Wish I had some better news for you.
